version: '3.8'
services:
  db:
    image: postgres:15
    container_name: job-db
    environment:
      POSTGRES_DB: jobcopilot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"